### ISSUE TITLE
Unable to reach Sentry log server: timed out

### ISSUE THREAD

**Issue by wh5a** [dahlia/sentry-heroku#4]
I set up a sentry server on heroku using your code and it works fine mostly. I'm able to log messages into sentry from Python/Django code. However I always get the following error when the raven library delivers to sentry server. I'm not sure if this means anything bad, as I still see an entry added in the sentry server.

Unable to reach Sentry log server: timed out (url: http://send2china.herokuapp.com//api/1/store/)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/raven/transport/threaded.py", line 104, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/lib/python2.7/site-packages/raven/transport/http.py", line 49, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 62, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
Failed to submit message: u'ZeroDivisionError: integer division or modulo by zero'

**Comment by dahlia** [comment]
It’s probably because Sentry on Heroku doesn’t immediately respond.  It’s [one of well-known problems](https://devcenter.heroku.com/articles/dynos#dyno-sleeping) of Heroku.
